import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const home = await mkdtemp(join(tmpdir(), "dsh-usage-stats-install-"));
const installer = fileURLToPath(new URL("./install.mjs", import.meta.url));
const patchPath = join(home, "profiles", "web", "cordis.patch.yml");
const pluginEntry = /^\s+name:\s*dsh-usage-stats\s*$/gm;

function run(...args) {
	const result = spawnSync(process.execPath, [installer, ...args], {
		env: { ...process.env, DSH_HOME: home },
		encoding: "utf8"
	});
	assert.equal(result.status, 0, result.stderr || result.stdout);
	return result.stdout;
}

function runFailure(...args) {
	const result = spawnSync(process.execPath, [installer, ...args], {
		env: { ...process.env, DSH_HOME: home },
		encoding: "utf8"
	});
	assert.notEqual(result.status, 0, "command should fail");
	return `${result.stderr}\n${result.stdout}`;
}

try {
	run();
	run();
	assert.match(run("--check"), /Verified dsh-usage-stats@/);
	let patch = await readFile(patchPath, "utf8");
	assert.equal([...patch.matchAll(pluginEntry)].length, 1, "installer must be idempotent");

	// A freshly generated Harness patch can be the YAML empty sequence `[]`.
	// Appending `- insert:` after it creates an invalid document; replace the
	// empty root while preserving any surrounding comments.
	await writeFile(patchPath, "[]\n", "utf8");
	run();
	patch = await readFile(patchPath, "utf8");
	assert.doesNotMatch(patch, /^\s*\[\]\s*$/m, "empty YAML sequence must be replaced, not appended to");
	assert.equal([...patch.matchAll(pluginEntry)].length, 1);
	run();
	assert.equal([...((await readFile(patchPath, "utf8")).matchAll(pluginEntry))].length, 1, "normalized empty patch must remain idempotent");

	await writeFile(patchPath, "# Harness patch entries\n\n[]\n", "utf8");
	run();
	patch = await readFile(patchPath, "utf8");
	assert.match(patch, /^# Harness patch entries$/m, "comments around an empty sequence must be preserved");
	assert.doesNotMatch(patch, /^\s*\[\]\s*$/m);
	assert.equal([...patch.matchAll(pluginEntry)].length, 1);

	await writeFile(patchPath, "[] # generated by Harness\n", "utf8");
	run();
	patch = await readFile(patchPath, "utf8");
	assert.match(patch, /^# generated by Harness$/m, "an inline comment on the empty sequence must be preserved");
	assert.doesNotMatch(patch, /^\s*\[\](?:\s+#.*)?$/m);
	assert.equal([...patch.matchAll(pluginEntry)].length, 1);
	run();
	assert.equal([...((await readFile(patchPath, "utf8")).matchAll(pluginEntry))].length, 1, "inline-comment normalization must remain idempotent");

	const brokenLegacyPatch = `[]

# dsh-usage-stats: token usage heatmap + DeepSeek balance
- insert:
    - id: usage-stats
      name: dsh-usage-stats
`;
	await writeFile(patchPath, brokenLegacyPatch, "utf8");
	assert.match(runFailure("--check"), /invalid YAML/, "check mode must reject the legacy broken shape");
	run();
	patch = await readFile(patchPath, "utf8");
	assert.doesNotMatch(patch, /^\s*\[\]\s*$/m, "normal installation must repair the legacy broken shape");
	assert.equal([...patch.matchAll(pluginEntry)].length, 1);

	await writeFile(patchPath, brokenLegacyPatch.replace("[]", "[] # generated by Harness"), "utf8");
	assert.match(runFailure("--check"), /invalid YAML/, "check mode must reject an inline-comment legacy conflict");
	run();
	patch = await readFile(patchPath, "utf8");
	assert.match(patch, /^# generated by Harness$/m);
	assert.doesNotMatch(patch, /^\s*\[\](?:\s+#.*)?$/m);
	assert.equal([...patch.matchAll(pluginEntry)].length, 1);

	const existing = "- insert:\n    - id: existing-plugin\n      name: existing-plugin\n";
	await writeFile(patchPath, existing, "utf8");
	run();
	patch = await readFile(patchPath, "utf8");
	assert.match(patch, /name: existing-plugin/, "existing patch entries must be preserved");
	assert.equal([...patch.matchAll(pluginEntry)].length, 1);
	const installed = JSON.parse(await readFile(join(home, "profiles", "node_modules", "dsh-usage-stats", "package.json"), "utf8"));
	assert.equal(installed.name, "dsh-usage-stats");
	assert.equal(installed.dsh?.bundle?.patch, "./cordis.patch.yml");
	assert.match(
		await readFile(join(home, "profiles", "node_modules", "dsh-usage-stats", "cordis.patch.yml"), "utf8"),
		/^\s+name:\s*dsh-usage-stats\s*$/m
	);
	assert.equal(await readFile(join(home, "profiles", "node_modules", "dsh-usage-stats", "lib", "index.js"), "utf8").then((text) => text.length > 1000), true);
	console.log("INSTALLER REGRESSION TESTS PASSED");
} finally {
	await rm(home, { recursive: true, force: true });
}